version: '3'
services:
    nginx:
        image: nginx:1.11
        ports:
            - "82:80"
        links:
            - php
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./:/usr/share/nginx/html # NGINX also needs access to serve statics
        environment:
            - VIRTUAL_HOST=*.mariokart.fun
    php:
        build:
            context: .
            dockerfile: ./docker/Dockerfile-php
        ports:
            - "10001:9000"
        volumes:
            - ./:/usr/share/nginx/html
    php-phinx:
        build:
            context: .
            dockerfile: ./docker/Dockerfile-phpcli
            # Wait until composer is done then execute phinx and other commands
        command: bash -c "sleep 10; /usr/share/nginx/html/docker/run.sh"
        volumes:
            - ./:/usr/share/nginx/html
    composer:
        image: composer/composer
        volumes:
            - .:/app
        command: install
    mysql:
        image: mysql:5.7
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=mariokart
            - MYSQL_USER=local
            - MYSQL_PASSWORD=local
        volumes:
             - localmysql:/var/lib/mysql # Persist database when destroying containers

# This allows us to persist the volume between containers being wiped etc
# Requires you to run the command 'docker volume create localmysql' FIRST!!!'
volumes:
    localmysql:
        external: true

# Connect this container to the rest of the stack (DIG-website)
networks:
    default:
        external:
            name: local
