version: '3'
services:
    nginx:
        image: nginx:1.11
        ports:
            - "80"
        links:
            - php
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./:/usr/share/nginx/html # NGINX also needs access to serve statics
        environment:
            - VIRTUAL_HOST=www.mariokart.fun,mariokart.fun,dev.mariokart.fun
        restart: always
    php:
        build:
            context: .
            dockerfile: ./docker/Dockerfile-php
        ports:
            - "9000"
        volumes:
            - ./:/usr/share/nginx/html
        restart: always
    php-phinx:
        build:
            context: .
            dockerfile: ./docker/Dockerfile-phpcli
            # Wait until composer is done then execute phinx and other commands
        command: bash -c "sleep 10; /usr/share/nginx/html/docker/run.sh"
        volumes:
            - ./:/usr/share/nginx/html
# Connect this container to the rest of the stack (DIG-website)
networks:
    default:
        external:
            name: local
