FROM php:7.1-fpm

RUN apt-get update && apt-get install -y \
        libfreetype6-dev \
        libmcrypt-dev \
        libcurl4-openssl-dev \
        libxml2-dev \
        git \
    && docker-php-ext-install -j$(nproc) curl fileinfo exif json mbstring pdo pdo_mysql posix xml zip \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN pecl install xdebug-2.5.0 && docker-php-ext-enable xdebug
